set(__QT_DEPLOY_TARGET_SimpleFileExplorer_FILE /Users/etsuko/Application/explorer/build_simple/SimpleFileExplorer.app/Contents/MacOS/SimpleFileExplorer)
set(__QT_DEPLOY_TARGET_SimpleFileExplorer_TYPE EXECUTABLE)
